hydra:
  run:
    dir: s3_config/exercise_files/hydra_logging/${now:%Y-%m-%d/%H-%M-%S}

hparams:
  batch_size: 100
  x_dim: 784
  hidden_dim: 50
  latent_dim: 20
  lr: 5e-3
  epochs: 2
  seed: 2137 
  dataset_path: "~/datasets"
