name: "Is sorted?"

on:
  push:
  pull_request:

jobs:
  build-on-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: Restore Cache
      uses: actions/cache@v2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with isort
      run: |
        pip install isort
        isort -v

  build-on-windows:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with isort
      run: |
        pip install isort
        isort -v